name: spring-auth app

on:
  push:
    branches: [ master ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${HOSTNAME} '
          
            rm -rf /home/ubuntu/spring-auth
            git clone git@github.com:billkariri-experimental/spring-auth.git
            cd /home/ubuntu/spring-auth 
            git checkout master
            git pull origin master 
            mkdir -p /home/ubuntu/logs 
            fuser -k 8972/tcp 
            /opt/apache-maven-3.8.7/bin/mvn clean compile package -DskipTests 
            cd /home/ubuntu/spring-auth/target
            nohup java -jar *jar &
            exit 0
          '
