name: spring-auth app

on:
  push:
    branches: [ master ]

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{secrets.SSH_KEY}}
          HOSTNAME : ${{secrets.HOSTNAME}}
          USER_NAME: ${{secrets.USERNAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o ServerAliveInterval=300 -i private_key ${USER_NAME}@${HOSTNAME} '
          
            rm -rf /home/ubuntu/spring-auth
            git clone git@github.com:billkariri-experimental/spring-auth.git
            cd /home/ubuntu/spring-auth 
            git checkout master
            git pull origin master 
            mkdir -p /home/ubuntu/logs 
            sudo chmod +x ./deploy.sh
            ./deploy.sh
          '