name: spring-auth app

on:
  push:
    branches: [ master ]

jobs:
  #First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on vps
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOSTNAME}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.PORT}}
          script: |
            mkdir -p /home/ubuntu/logs
            cd /home/ubuntu/spring-auth
            git checkout master
            git pull origin master
